#!/usr/bin/env bash
set -e
. "$BCLI_WORKDIR/common"

[ ! -n "$1" ] && cli_help deploy


cli_log "Deployment BEGIN"

cli_log "ENV variables"

cli_log "Executing helm upgrade --install ..."
# Example
# helm upgrade --install \
#   --wait \
#   --values $BAGCLI_PROJECTS_PATH/$BAGCLI_PROJECT_NAME/values.yaml \
#   --namespace $BAGCLI_K8S_NAMESPACE $BAGCLI_PROJECT_NAME $BAGCLI_REPO_PATH

cli_log "Deployment END"
